### ISSUE TITLE
Unhandled exception has occured in your application. (help)

### ISSUE THREAD

**Issue by 1red-ryu** [SoapyMan/FLRecordingCleaner#1]
Hey @SoapyMan, l'm sure this program works & I just don't know how to use it so if you could help me...I installed flparser using the git command, opened FLRecordingCleaner.exe , set the file path and clicked "Gather Information" and I got an error that says:

"Unhandled exception has occured in our applicatoin. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.
Invalid URL: The format of the URL could not be determined."

 Of course after clicking continue nothing works. I simply have no idea what I'm looking at, I'd appreciate your help.

In the Detail dropdown, this is what comes up:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at FLRecordingCleaner.Helpers.NormalizePath(String path)
   at FLRecordingCleaner.Form1.bgWorker_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
FLRecordingCleaner
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/**user**/Downloads/FLRecordingCleaner/FLRecordingCleaner.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4320.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Monad.FLParser
    Assembly Version: 0.1.6673.2444
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/**username**/Downloads/FLRecordingCleaner/Monad.FLParser.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

[FLRC error.txt](https://github.com/SoapyMan/FLRecordingCleaner/files/6167660/FLRC.error.txt)

**Comment by 1red-ryu** [comment]
@demberto @ronnyamelo @dany68 could any of you help?

**Comment by SoapyMan** [comment]
Must be a path issue, maybe it's very long. It fails exactly in the `FLRecordingCleaner.Helpers.NormalizePath(String path)`. Can't know without analyzing the folder structure.

**Comment by 1red-ryu** [comment]
How would I solve this?

**Comment by SoapyMan** [comment]
@muneymercer Hey! It seemed like my FL20 projects was causing that problem too so I've tried to fix this:
I hope it works
https://github.com/SoapyMan/FLRecordingCleaner/releases/tag/1.01

**Comment by 1red-ryu** [comment]
> 

 Hey @SoapyMan , I've just come back to this and it actually still doesn't work for me. I'd really appreciate additional help..

The bugfixed FLRecordingCleaner is in my Downloads folder, with the same contents you uploaded.
Still the same exception text...Any clue what I'm doing wrong? Maybe a dependency that is not installed correctly?

```
************** Exception Text **************
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at FLRecordingCleaner.Helpers.NormalizePath(String path)
   at FLRecordingCleaner.ProjectWorker.CollectProjectData(ProjectInfo project)
   at FLRecordingCleaner.MainForm.bgWorker_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

```
